### ISSUE TITLE
20words_mean_face.npy

### ISSUE THREAD

**Issue by Wertiz** [gilikn/FacePipe#1]
Could you provide the `20words_mean_face.npy` you used?

**Comment by gilikn** [comment]
Hi there!
This file can be downloaded from the following URL, as provided in the facepipe/config/pre_processing_config.py configuration file:
```
MEAN_FACE_DOWNLOAD_URL = "https://github.com/mpc001/Lipreading_using_Temporal_Convolutional_Networks/blob/master/preprocessing/20words_mean_face.npy"
```
Let me know if there is anything else.
